### ISSUE TITLE
example of post in laravel

### ISSUE THREAD

**Issue by taylormaguire** [spinen/connectwise-php-client#13]
wondering if there is an example of using this to post data to connectwise from laravel. unclear how to add the JSON Body.

**Comment by jimmypuckett** [comment]
@taylormaguire,

I am sorry for the delay, we have had a few projects that are eating us alive.  Anyhow, we are about to get on a big project that is going to be using this client, so we will be refining it.

We will add better documentation at that time.

Thanks.

**Comment by jimmypuckett** [comment]
Duplicate of #1
