### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by mcdemon** [spinen/connectwise-php-client#14]
I apologize in advance if this is not the correct place to post this.  Can someone please advise what values should be used for the integrator and  password when setting up outside of Laravel?
$client->setIntegrator('<integrator>')->setPassword('<password>')

**Comment by jimmypuckett** [comment]
@mcdemon Thanks for reaching out.

If you have a developer account, you can read about the integration here...

https://developer.connectwise.com/Manage/Developer_Guide

But they don't really get into how to set up the account.  You do that under the `Setup Tables > Integrator Login List` in the ConnectWise application.

**Comment by mcdemon** [comment]
Perfect. Thank you for the quick response.

Matthew
M - 203-751-7178

________________________________
