### ISSUE TITLE
Unexpected 'var_export' error - Revisited

### ISSUE THREAD

**Issue by mcdemon** [spinen/connectwise-php-client#24]
This is the continuation of a closed issue with the same title.  My apologies but I got sidetracked onto another project.  I have circled back to getting this configured on my WAMP test box and I continue to get the errors at:

 var_export($info->toArray(), false);

Parse error: syntax error, unexpected 'var_export' (T_STRING) in php shell code on line 15
php > array (
php (   'version' => 'v2016.6.43325',
php (   'isCloud' => false,
php (   'serverTimeZone' => 'Eastern Standard Time',
php ( )

The subsequent var_export commands return the same errors.

Any additional guidance is appreciated.

Thanks in advance.

**Comment by jimmypuckett** [comment]
Can you please post the code that you are using to set `$info`?

**Comment by mcdemon** [comment]
Hi Jimmy,

Here is the code from setting $info through the error I receive:

php > $info = $client->get('system/info');
POST /v4_6_release/apis/3.0/system/members/XXXXXXXXXXX/tokens HTTP/1.1
User-Agent: GuzzleHttp/6.3.3 curl/7.59.0 PHP/7.2.10
Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Host: cw.XXXXXXXXXX.com
x-cw-usertype: integrator

GET /v4_6_release/apis/3.0/system/info HTTP/1.1
User-Agent: GuzzleHttp/6.3.3 curl/7.59.0 PHP/7.2.10
Authorization: Basic XXXXXXXXXXXXXX
Host: cw.XXXXXXXXXX.com

php > var_export($info, false);
NULL
php > Spinen\ConnectWise\Models\System\Info::__set_state(array(
php (    'casts' =>
php (   array (
php (     'version' => 'string',
php (     'isCloud' => 'boolean',
php (     'serverTimeZone' => 'string',
php (   ),
php (    'attributes' =>
php (   array (
php (     'version' => 'v2016.6.43325',
php (     'isCloud' => false,
php (     'serverTimeZone' => 'Eastern Standard Time',
php (   ),
php ( ))
php > var_export($info->toArray(), false);

Parse error: syntax error, unexpected 'var_export' (T_STRING) in php shell code on line 15
php > array (
php (   'version' => 'v2016.6.43325',
php (   'isCloud' => false,
php (   'serverTimeZone' => 'Eastern Standard Time',
php ( )

Periodically, I encounter a different error first, then the 'unexpected var_export' error by running the same command a second time:

php>  var_export($info->toArray(), false);

Warning: Uncaught Error: Call to a member function toArray() on null in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1
php > array (
php (   'version' => 'v2016.6.43325',
php (   'isCloud' => false,
php (   'serverTimeZone' => 'Eastern Standard Time',
php ( )
php > var_export($info->toArray(), false);

Parse error: syntax error, unexpected 'var_export' (T_STRING) in php shell code on line 6
php > array (
php (   'version' => 'v2016.6.43325',
php (   'isCloud' => false,
php (   'serverTimeZone' => 'Eastern Standard Time',
php ( )
php >                                                      
Thanks

**Comment by jimmypuckett** [comment]
@mcdemon,

I am really not sure why you are seeing this error, but I do see the you appear to be on a really old version `2016.6.43325` of CW.  This maybe some issue with the version you are on?

Anyhow, I just did the following (on a Mac)...

```php
>>> $token = new Spinen\ConnectWise\Api\Token();
=> Spinen\ConnectWise\Api\Token {#3526}
>>> $guzzle = new GuzzleHttp\Client();
=> GuzzleHttp\Client {#3536}
>>> $resolver = new Spinen\ConnectWise\Support\ModelResolver();
=> Spinen\ConnectWise\Support\ModelResolver {#3548}
>>> $client = new Spinen\ConnectWise\Api\Client($token, $guzzle, $resolver);
=> Spinen\ConnectWise\Api\Client {#3555}
>>> $token->setCompanyId('*****')->setMemberId('*****');
=> Spinen\ConnectWise\Api\Token {#3526}
>>> $client->setIntegrator('*****')->setPassword('*****')->setUrl('https://*****');
=> Spinen\ConnectWise\Api\Client {#3555}
>>> $info = $client->get('system/info');
=> Spinen\ConnectWise\Models\System\Info {#3560}
>>> var_export($info->toArray(), false);
array (
  'version' => 'v2018.6.59996',
  'isCloud' => false,
  'serverTimeZone' => 'Eastern Standard Time',
  'licenseBits' =>
  array (
    0 =>
    array (
      'name' => 'PocketPC',
      'activeFlag' => true,
    ),
    1 =>
    array (
      'name' => 'EmailConnector',
      'activeFlag' => true,
    ),
    2 =>
    array (
      'name' => 'ADPInterface',
      'activeFlag' => false,
    ),
    3 =>
    array (
      'name' => 'GLInterface',
      'activeFlag' => true,
    ),
    4 =>
    array (
      'name' => 'PremiumPortal',
      'activeFlag' => true,
    ),
    5 =>
    array (
      'name' => 'ManagedServices',
      'activeFlag' => true,
    ),
    6 =>
    array (
      'name' => 'SpamStats',
      'activeFlag' => false,
    ),
    7 =>
    array (
      'name' => 'AuditTrail',
      'activeFlag' => true,
    ),
    8 =>
    array (
      'name' => 'QuoteWerks',
      'activeFlag' => false,
    ),
    9 =>
    array (
      'name' => 'ConnectWiseNetwork',
      'activeFlag' => true,
    ),
    10 =>
    array (
      'name' => 'Inventory',
      'activeFlag' => true,
    ),
    11 =>
    array (
      'name' => 'Purchasing',
      'activeFlag' => true,
    ),
    12 =>
    array (
      'name' => 'IzendaReports',
      'activeFlag' => true,
    ),
    13 =>
    array (
      'name' => 'SalesManagement',
      'activeFlag' => true,
    ),
    14 =>
    array (
      'name' => 'KnowledgeBase',
      'activeFlag' => true,
    ),
    15 =>
    array (
      'name' => 'Agreement',
      'activeFlag' => true,
    ),
    16 =>
    array (
      'name' => 'AgileBoard',
      'activeFlag' => true,
    ),
    17 =>
    array (
      'name' => 'Marketing',
      'activeFlag' => true,
    ),
    18 =>
    array (
      'name' => 'StreamlineIT',
      'activeFlag' => true,
    ),
    19 =>
    array (
      'name' => 'Subcontractor',
      'activeFlag' => true,
    ),
    20 =>
    array (
      'name' => 'CustomFields',
      'activeFlag' => true,
    ),
    21 =>
    array (
      'name' => 'ManageLogin',
      'activeFlag' => true,
    ),
  ),
  'cloudRegion' => 'NA',
)⏎
=> null
>>>
```

**Comment by jimmypuckett** [comment]
Closing this as it appears to be an issue with an unsupported version of CW
