### ISSUE TITLE
HTTP Exception echos response body and headers into browser

### ISSUE THREAD

**Issue by dlegatt** [spinen/connectwise-php-client#36]
https://github.com/spinen/connectwise-php-client/blob/2f3e481e88b2fae2f850886877199b4b096b1c86/src/Api/Client.php#L389

The method referenced in the line above results in the full request headers being dumped into the browser, which reveals the authentication token to the user. Wouldn't it be better to re-throw the exception instead so the app can handle it without leaking sensitive data? I can submit a pull request if needed.

**Comment by jimmypuckett** [comment]
Ya, that is not very wise.  We dropped that in as we were coding & never looked back. I am not even sure why the `if` is in there.

I will make it just re-throw for now.

Thanks.

**Comment by jimmypuckett** [comment]
Just tagged `5.1.3`

**Comment by dlegatt** [comment]
Awesome, thanks!
