### ISSUE TITLE
Install error with Laravel 8.9.0

### ISSUE THREAD

**Issue by cpelon** [spinen/connectwise-php-client#47]
When I run composer require spinen/connectwise-php-client
.....
  Problem 1
    - Installation request for spinen/connectwise-php-client ^5.5 -> satisfiable by spinen/connectwise-php-client[5.5.0, 5.5.1, 5.5.2, 5.5.3].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].

Installation failed, reverting ./composer.json to its original content.

composer.json
"require": {
        "php": "^7.3",
        "aws/aws-sdk-php": "^3.156",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.2.0",
        "laravel/framework": "^8.0",
        "laravel/jetstream": "^1.3",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.0",
        "livewire/livewire": "^2.0"
},

Laravel will not let me downgrade to guzzle 6.5.x-dev

**Comment by ssfinney** [comment]
@cpelon This is done and tagged at v. 5.5.4
