### ISSUE TITLE
Any chance of updating the Model for 2020.x versions of CW?

### ISSUE THREAD

**Issue by gooseleggs** [spinen/connectwise-php-client#51]
Hello

Just wondering if you have it on the roadmap to update to the later versions of the CW definition, as I see it getting a bit behind.

Thanks for an excellent package.

Kelvin

**Comment by jimmypuckett** [comment]
@gooseleggs last year ConnectWise really changed the json spec file that describes the api endpoints, so our client generator no longer works. They allow you to pass the version of the api in the request, so for us we have gotten by with the older api on newer servers. 

Are there specific items that are stale?

We have a new generator that is about 1/2 done, so maybe we can dust it off soon.
